-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- Due to circular dependencies, the order in which Schema Diff writes objects may not be optimal 
-- and manual changes to the script may be required to ensure changes are applied in the correct order.
-- Please report any issues along with steps to reproduce. 
BEGIN; 
ALTER TABLE IF EXISTS public."User"
    ADD COLUMN "Removed" boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS public."Component"
    ADD COLUMN "Removed" boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS public."Component" DROP CONSTRAINT IF EXISTS "FK_STATION";

ALTER TABLE IF EXISTS public."Component"
    ADD CONSTRAINT "FK_STATION" FOREIGN KEY ("StationId")
    REFERENCES public."Station" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS public."Alert" DROP CONSTRAINT IF EXISTS "Alert_FK_Station";

ALTER TABLE IF EXISTS public."Alert"
    ADD CONSTRAINT "Alert_FK_Station" FOREIGN KEY ("StationUid")
    REFERENCES public."Station" ("Uid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS public."Station"
    ADD COLUMN "Removed" boolean NOT NULL DEFAULT false;
CREATE OR REPLACE VIEW public."vEventDataLast"
 AS
 SELECT ed."HardwareId",
    ed1."Payload" AS "LastPayload",
    ed."LastReceivedTs",
    ed."FirstReceivedTs"
   FROM ( SELECT "EventData"."HardwareId",
            max("EventData"."Id") AS "Id",
            max("EventData"."ReceivedTs") AS "LastReceivedTs",
            min("EventData"."ReceivedTs") AS "FirstReceivedTs"
           FROM "EventData"
          GROUP BY "EventData"."HardwareId") ed
     JOIN "EventData" ed1 ON ed."Id" = ed1."Id";

ALTER TABLE public."vEventDataLast"
    OWNER TO postgres;



-- Changing the columns in a view requires dropping and re-creating the view.
-- This may fail if other objects are dependent upon this view,
-- or may cause procedural functions to fail if they are not modified to
-- take account of the changes.
DROP VIEW public."vComponentLast";

CREATE OR REPLACE VIEW public."vComponentLast"
    AS
     SELECT cn."DisplayName",
    cn."ShortName",
    cn."HardwareId",
    cn."Type",
    cn."StationId",
    cn."MinValue",
    cn."MaxValue",
    cn."DisplayUnit",
    cn."DisplayOrder",
    cn."AdjustmentFunction",
    y."LastPayload",
    y."LastReceivedTs",
    y."FirstReceivedTs"
   FROM ( SELECT "vEventDataLast"."HardwareId",
            "vEventDataLast"."LastPayload",
            "vEventDataLast"."LastReceivedTs",
            "vEventDataLast"."FirstReceivedTs"
           FROM "vEventDataLast"
        UNION
         SELECT cc."HardwareId",
            NULL::character varying AS "LastPayload",
            NULL::timestamp without time zone AS "LastReceivedTs",
            NULL::timestamp without time zone AS "FirstReceivedTs"
           FROM "Component" cc
          WHERE NOT (cc."HardwareId"::text IN ( SELECT DISTINCT "EventData"."HardwareId"
                   FROM "EventData"))) y
     JOIN "Component" cn ON cn."HardwareId"::text = y."HardwareId"::text
UNION
 SELECT cn."DisplayName",
    cn."ShortName",
    concat(cn."HardwareId", '#')::character varying(36) AS "HardwareId",
    'CO'::character varying AS "Type",
    cm."StationId",
    0 AS "MinValue",
    999999999 AS "MaxValue",
    cn."DisplayUnit",
    cn."DisplayOrder",
    cn."AdjustmentFunction",
    cn."Count"::text AS "LastPayload",
    cn."LastTs" AS "LastReceivedTs",
    NULL::timestamp without time zone AS "FirstReceivedTs"
   FROM "Counter" cn
     JOIN "Component" cm ON cn."HardwareId"::text = cm."HardwareId"::text;

ALTER TABLE public."vComponentLast"
    OWNER TO postgres;


END;