-- This script was partly generated by the Schema Diff utility in pgAdmin 4.
-- Updates a Sentraq database from version 1.0.3 (april 2026) to 1.1.0 (July 2026)
--rollback;
BEGIN;

-- ### Tabellen ############

 ALTER TABLE IF EXISTS public."Component"
    ADD COLUMN "Visible" boolean NOT NULL DEFAULT true;

ALTER TABLE IF EXISTS public."Component" DROP CONSTRAINT IF EXISTS "Component_CK_Type";

ALTER TABLE IF EXISTS public."Component"
    ADD CONSTRAINT "Component_CK_Type" CHECK ("Type"::text = ANY (ARRAY['FI'::character varying::text, 'FL'::character varying::text, 'AC'::character varying::text, 'SW'::character varying::text, 'CO'::character varying::text, 'SE'::character varying::text, 'DI'::character varying::text]));
ALTER TABLE IF EXISTS public."Station"
    ADD COLUMN "MaintenanceActiveAlertSentTs" timestamp without time zone;

ALTER TABLE IF EXISTS public."Station"
    ADD COLUMN "MaintenanceActiveSinceTs" timestamp without time zone;

ALTER TABLE IF EXISTS public."Station"
    ADD COLUMN "Visible" boolean NOT NULL DEFAULT true;

ALTER TABLE IF EXISTS public."User"
   ADD COLUMN "PasskeyIdent" character varying(1000) COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public."User"
    ADD COLUMN "PasskeyRequestCode" character varying(100) COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public."User"
    ADD COLUMN "PasskeyRequestTs" timestamp without time zone;


-- ### Views ############

DROP VIEW IF EXISTS public."vAggregationSum1d";
DROP VIEW IF EXISTS public."vAggregationSum1h";
DROP VIEW IF EXISTS public."vEventDataExport";
DROP VIEW IF EXISTS public."vAggregationSum5m";
DROP VIEW IF EXISTS public."vAggregationAvg5m";
DROP VIEW IF EXISTS public."vAggregationAvg1h";
DROP VIEW IF EXISTS public."vAggregationAvg1d";
DROP VIEW IF EXISTS public."vComponentLast";
DROP VIEW IF EXISTS public."vAlert";
DROP VIEW IF EXISTS public."vStation";


CREATE OR REPLACE VIEW public."vAggregationAvg5m"
 AS
 SELECT ed."HardwareId",
    date_bin('00:05:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    avg(ed."Payload"::double precision) AS value
   FROM "EventData" ed
     JOIN "Component" co ON co."HardwareId"::text = ed."HardwareId"::text
  WHERE (co."Type"::text = ANY (ARRAY['FI'::character varying::text, 'SE'::character varying::text])) AND co."Removed" = false
  GROUP BY ed."HardwareId", (date_bin('00:05:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationAvg5m"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationAvg5m" TO postgres;
GRANT SELECT ON TABLE public."vAggregationAvg5m" TO sensql;


CREATE OR REPLACE VIEW public."vAggregationSum5m"
    AS
     SELECT ed."HardwareId",
    date_bin('00:05:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    sum(ed."Payload"::double precision) / (count(*)::double precision / 5::double precision) AS value,
    count(*) AS cnt
   FROM "EventData" ed
     JOIN "Component" co ON co."HardwareId"::text = ed."HardwareId"::text
  WHERE (co."Type"::text = ANY (ARRAY['AC'::character varying::text, 'SW'::character varying::text])) AND co."Removed" = false
  GROUP BY ed."HardwareId", (date_bin('00:05:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationSum5m"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationSum5m" TO postgres;
GRANT SELECT ON TABLE public."vAggregationSum5m" TO sensql;


CREATE OR REPLACE VIEW public."vAggregationSum1d"
    AS
     SELECT "HardwareId",
    date_bin('24:00:00'::interval, date_bin, '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    sum(value) AS value
   FROM "vAggregationSum5m" ed
  GROUP BY "HardwareId", (date_bin('24:00:00'::interval, date_bin, '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationSum1d"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationSum1d" TO postgres;
GRANT SELECT ON TABLE public."vAggregationSum1d" TO sensql;


CREATE OR REPLACE VIEW public."vAggregationSum1h"
    AS
     SELECT "HardwareId",
    date_bin('01:00:00'::interval, date_bin, '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    sum(value) AS value
   FROM "vAggregationSum5m" ed
  GROUP BY "HardwareId", (date_bin('01:00:00'::interval, date_bin, '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationSum1h"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationSum1h" TO postgres;
GRANT SELECT ON TABLE public."vAggregationSum1h" TO sensql;


CREATE OR REPLACE VIEW public."vAggregationAvg1h"
 AS
 SELECT ed."HardwareId",
    date_bin('01:00:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    avg(ed."Payload"::double precision) AS value
   FROM "EventData" ed
     JOIN "Component" co ON co."HardwareId"::text = ed."HardwareId"::text
  WHERE (co."Type"::text = ANY (ARRAY['FI'::character varying::text, 'CO'::character varying::text, 'SE'::character varying::text])) AND co."Removed" = false
  GROUP BY ed."HardwareId", (date_bin('01:00:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationAvg1h"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationAvg1h" TO postgres;
GRANT SELECT ON TABLE public."vAggregationAvg1h" TO sensql;


CREATE OR REPLACE VIEW public."vAggregationAvg1d"
 AS
 SELECT ed."HardwareId",
    date_bin('24:00:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone) AS date_bin,
    avg(ed."Payload"::double precision) AS value
   FROM "EventData" ed
     JOIN "Component" co ON co."HardwareId"::text = ed."HardwareId"::text
  WHERE (co."Type"::text = ANY (ARRAY['FI'::character varying::text, 'CO'::character varying::text, 'SE'::character varying::text])) AND co."Removed" = false
  GROUP BY ed."HardwareId", (date_bin('24:00:00'::interval, ed."ReceivedTs", '2001-01-01 00:00:00'::timestamp without time zone));

ALTER TABLE public."vAggregationAvg1d"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAggregationAvg1d" TO postgres;
GRANT SELECT ON TABLE public."vAggregationAvg1d" TO sensql;


CREATE OR REPLACE VIEW public."vEventDataExport"
 AS
 SELECT DISTINCT s1."DisplayName" AS "StationName",
    s1."Uid" AS "StationUid",
    c1."DisplayName" AS "ComponentName",
    c1."HardwareId",
    c1."Type" AS "ComponentType",
    ed1.date_bin AS "Received",
    c1."DisplayUnit" AS "Unit",
    ed1.value AS "Value"
   FROM "vAggregationAvg5m" ed1
     JOIN "Component" c1 ON c1."HardwareId"::text = ed1."HardwareId"::text
     JOIN "Station" s1 ON s1."Id" = c1."StationId"
UNION
 SELECT DISTINCT s2."DisplayName" AS "StationName",
    s2."Uid" AS "StationUid",
    c2."DisplayName" AS "ComponentName",
    c2."HardwareId",
    c2."Type" AS "ComponentType",
    ed2.date_bin AS "Received",
    c2."DisplayUnit" AS "Unit",
    ed2.value AS "Value"
   FROM "vAggregationSum5m" ed2
     JOIN "Component" c2 ON c2."HardwareId"::text = ed2."HardwareId"::text
     JOIN "Station" s2 ON s2."Id" = c2."StationId";

ALTER TABLE public."vEventDataExport"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vEventDataExport" TO postgres;
GRANT SELECT ON TABLE public."vEventDataExport" TO sensql;


CREATE OR REPLACE VIEW public."vComponentLast"
    AS
     SELECT cm."DisplayName",
    cm."ShortName",
    cm."HardwareId",
    cm."Type",
    cm."StationId",
    cm."MinValue",
    cm."MaxValue",
    cm."DisplayUnit",
    cm."DisplayOrder",
    cm."AdjustmentFunction",
    y."LastPayload",
    y."LastReceivedTs",
    y."FirstReceivedTs"
   FROM ( SELECT "vEventDataLast"."HardwareId",
            "vEventDataLast"."LastPayload",
            "vEventDataLast"."LastReceivedTs",
            "vEventDataLast"."FirstReceivedTs"
           FROM "vEventDataLast"
        UNION
         SELECT cc."HardwareId",
            NULL::character varying AS "LastPayload",
            NULL::timestamp without time zone AS "LastReceivedTs",
            NULL::timestamp without time zone AS "FirstReceivedTs"
           FROM "Component" cc
          WHERE NOT (cc."HardwareId"::text IN ( SELECT DISTINCT "EventData"."HardwareId"
                   FROM "EventData"))) y
     JOIN "Component" cm ON cm."HardwareId"::text = y."HardwareId"::text
  WHERE cm."Removed" = false AND cm."Visible" = true
UNION
 SELECT cn."DisplayName",
    cn."ShortName",
    concat(cn."HardwareId", '#')::character varying(36) AS "HardwareId",
    'CO'::character varying AS "Type",
    cm."StationId",
    0 AS "MinValue",
    999999999 AS "MaxValue",
    cn."DisplayUnit",
    cn."DisplayOrder",
    cn."AdjustmentFunction",
    cn."Count"::text AS "LastPayload",
    cn."LastTs" AS "LastReceivedTs",
    NULL::timestamp without time zone AS "FirstReceivedTs"
   FROM "Counter" cn
     JOIN "Component" cm ON cn."HardwareId"::text = cm."HardwareId"::text
  WHERE cm."Removed" = false AND cm."Visible" = true;

ALTER TABLE public."vComponentLast"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vComponentLast" TO postgres;
GRANT SELECT ON TABLE public."vComponentLast" TO sensql;


CREATE OR REPLACE VIEW public."vAlert"
 AS
 SELECT aa."Id",
    aa."StationUid",
    st."ShortName" AS "StationShortName",
    aa."FirstEventTs",
    aa."LastEventTs",
    aa."ConfirmedAt",
    aa."ConfirmedBy",
    aa."IsActive",
    aa."MailSendAt",
    y."Faults"
   FROM ( SELECT x."Id",
            string_agg(cc."DisplayName"::text, ', '::text) AS "Faults"
           FROM ( SELECT DISTINCT ed."HardwareId",
                    a."Id"
                   FROM "vEventData" ed
                     JOIN "vComponentLast" c ON c."HardwareId"::text = ed."HardwareId"::text AND c."Type"::text = 'FL'::text AND ed."Payload"::text <> '0'::text
                     JOIN "Alert" a ON a."StationUid"::text = ed."StationUid"::text
                  WHERE ed."ReceivedTs" >= a."FirstEventTs" AND ed."ReceivedTs" <= a."LastEventTs") x
             JOIN "Component" cc ON x."HardwareId"::text = cc."HardwareId"::text
          GROUP BY x."Id") y
     JOIN "Alert" aa ON aa."Id" = y."Id"
     JOIN "Station" st ON st."Uid"::text = aa."StationUid"::text;

ALTER TABLE public."vAlert"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vAlert" TO postgres;
GRANT SELECT ON TABLE public."vAlert" TO sensql;


CREATE OR REPLACE VIEW public."vStation"
    AS
     SELECT "Id",
    "DisplayName",
    "ShortName",
    "Latitude",
    "Longitude",
    "Type",
    "DisplayColor",
    "Uid",
    "DisplayOrder",
    "AlertReceiverEmailAddresses",
    "WatchdogHardwareId",
    "MaintenanceActiveSinceTs",
    COALESCE(( SELECT true
           FROM "Alert" a_1
          WHERE a_1."StationUid"::text = s."Uid"::text AND a_1."ConfirmedAt"::text IS NULL AND a_1."IsActive"::text = 'Y'::text), false) AS "HasActiveAlert"
   FROM "Station" s
  WHERE "Visible" = true;

ALTER TABLE public."vStation"
    OWNER TO postgres;

GRANT ALL ON TABLE public."vStation" TO postgres;
GRANT SELECT ON TABLE public."vStation" TO sensql;

END;